CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80

## Split keyboards
## https://zmk.dev/docs/config/system#split-keyboards
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

## Display Configuratoin
## https://zmk.dev/docs/config/displays
# CONFIG_ZMK_DISPLAY=n  

# ## Track words per minute
# CONFIG_ZMK_WPM=y